server:
  port: 8765
spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver: 
        jwt:
          # Especifica qual servidor de autorização está sendo usado
          # Este servidor de recursos usa essa propriedade para autoconfigurar-se ainda mais, descobrir as 
          # chaves públicas do servidor de autorização e, posteriormente, validar os JWTs recebidos
          issuer-uri: http://localhost:8181/realms/spring-boot-microservices-realm
  cloud:
    gateway:
      routes:
      ## Product Service Route
      - id: product-service
        uri: lb://product-service
        predicates: 
        - Path=/api/product
      ## Order Service Route
      - id: order-service
        uri: lb://order-service
        predicates: 
        - Path=/api/order
      ## Discover Server Route
      - id: discovery-server
        uri: http://localhost:8761
        predicates: 
        - Path=/eureka/web
        # Para que quando for feita uma solicitação para localhost:8765/eureka/web seja redirecionado para 
        # http://localhost:8761 e não para http://localhost:8761/eureka/web 
        filters: SetPath=/ 
      ## Discover Server Static Resources Route
      ## Para carregar os recusos estáticos do discovery. Ex: CSS e javascript
      - id: discovery-server-static
        uri: http://localhost:8761
        predicates: 
        - Path=/eureka/**

app:
  eureka-server: localhost
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

logging:
  level:
    root: INFO
    springframework:
      cloud:
        gateway:
          route:
            RouteDefinition:
              Locator: INFO
          nodeValue: TRACE
        
  