spring:
  data:
    mongodb:
      uri: mongodb://adm:123@localhost:27017/product-service?authSource=admin
  application:
    name: product-service
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka      