spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
  application:
    name: inventory-service
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka # Para que o client possa encontrar o Eureka Server   
server:
  port: 8082